name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'

categories:
  - title: ':wrench: Build'
    labels:
      - 'build'

  - title: ':boar: Chore'
    labels:
      - 'dependencies'
      - 'chore'

  - title: ':green_heart: CI'
    labels:
      - 'ci'

  - title: ':books: Documentation'
    labels:
      - 'docs'

  - title: ':star: Features'
    labels:
      - 'feat'

  - title: ':beetle: Bug Fixes'
    labels:
      - 'fix'

  - title: ':zap: Performance'
    labels:
      - 'perf'

  - title: ':recycle: Refactor'
    labels:
      - 'refactor'

  - title: ':white_check_mark: Test'
    labels:
      - 'test'

template: |
  $CHANGES
